version: '3.8'

services:
    nftbridge-mongo:
        image: nftbridge-mongo
        build:
            context: ./mongoDb
            dockerfile: Dockerfile
        restart: always
        ports:
            - "27020:27017"
        command: [--auth]   
        environment: 
            MONGO_INITDB_ROOT_USERNAME: nftbridge_admin
            MONGO_INITDB_ROOT_PASSWORD: nftbridge_pwd
    nftbridge-backend:
        image: nftbridge-backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8331:8331"
        depends_on:
            - nftbridge-mongo
        environment:
            - MONGO_URI=mongodb://nftbridge_admin:nftbridge_pwd@nftbridge-mongo/nftbridge-backend
            - NODE_ENV=staging
        restart: always
